apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      serviceAccountName: web-app-service-account  # Binding the cluster-admin cluster role to the web-app via the created service account
      containers:
      - name: web-app
        image: stanhoe/tasky:demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo_admin:mongo_password@mongo_ip:27017/mongo_database"
        - name: SECRET_KEY
          value: "secret-key"
